name: GitHub Actions Auto Health Report
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Run script on daily 7:00am
  schedule:
    - cron: '00 23 * * *'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-ocr.txt ]; then pip install -r requirements.txt; fi
      - name: Run script
        run: |
          python report-ocr.py

